name: 03SPD-TST

on:
  schedule:
  - cron: '15 18 * * *' 
  workflow_dispatch:
    分支:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install numpy          
  
        
      - name: Run iptv
        run: python ${{ github.workspace }}/ZUZU-PY/#SPED-TST.py
